language: node_js
node_js: "node"
install:
  - npm install
script:
 - npm test
 - npm run flow
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      sudo: required
      node_js: false
      before_install:
        - nvm install 7
      android:
        components:
          - tools
          - platform-tools
          - build-tools-23.0.1
          - android-23
          - build-tools-26.0.1
          - android-26
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
      script:
        - cd android && ./gradlew assembleDebug && ./gradlew assembleRelease
deploy:
  provider: testfairy
  api-key: $API_KEY
  app-file: android/app/build/outputs/apk/app_release.apk
  keystore-file: android/app/my-release-key.keystore
  alias: android