/**@flow */
import React, { Component } from 'react';
import { View, Text } from 'react-native';
import { Button } from 'react-native-elements';
import { connect } from 'react-redux';
import Picker from 'react-native-modal-selector';
import PushNotification from 'react-native-push-notification';
import DatePicker from 'react-native-datepicker';
import { menuItemNames } from './Menu';
import { addUserAppointmentsAction } from '../state/actions/user-appointments-action';
import FirebaseClient from '../services/firebase-client';
import { APP_COLORS } from '../config/app-palette';

type PopsType = {
    staffAvailable: string[],
    uid: string,
    addUserAppointment: any,
    onButtonPressed: any
}
type StateType = {
    datetime: string,
    staff: string
}
class AppointmentDetails extends Component<PopsType, StateType> {
    firebase = FirebaseClient.getClient();
    state = {
        datetime: '',
        staff: ''
    }
    onAppointmentSaved() {
        this.props.addUserAppointment(this.props.uid, this.state);
        PushNotification.localNotification({
            /* Android Only Properties */
            id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
            ticker: "My Notification Ticker", // (optional)
            autoCancel: true, // (optional) default: true
            largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
            smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
            bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
            subText: "This is a subText", // (optional) default: none
            color: "red", // (optional) default: system default
            vibrate: true, // (optional) default: true
            vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
            tag: 'some_tag', // (optional) add tag to message
            group: "group", // (optional) add group to message
            ongoing: false, // (optional) set whether this is an "ongoing" notification
            /* iOS and Android properties */
            title: "My Notification Title", // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
            message: "My Notification Message", // (required)
            playSound: false, // (optional) default: true
            soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
            number: 10, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
            repeatType: 'day', // (Android only) Repeating interval. Could be one of `week`, `day`, `hour`, `minute, `time`. If specified as time, it should be accompanied by one more parameter 'repeatTime` which should the number of milliseconds between each interval
            actions: '["Yes", "No"]',  // (Android only) See the doc for notification actions to know more
        });
    }
    render() {
        const { labelStyle,
            dateStyle,
            selectStyle } = styles;


        const staffAvailable = this.props.staffAvailable.map(
            (employee, index) => ({
                index,
                key: index,
                value: employee,
                label: employee
            })
        )

        return (
            <View
                style={{
                    flex:1,
                    justifyContent: 'center',
                    paddingLeft: 10,
                    paddingRight: 10
                }}>
                <View style={{
                    flex: 1,
                    marginTop: 20
                }}>
                    <Picker
                        data={staffAvailable}
                        initValue="Please select the specialist"
                        style={selectStyle}
                        cancelText={`Cancel`}
                        onChange={(staff => this.setState({ staff: staff.value }))} />
                </View>
                <View
                    style={{
                        flex: 1,
                        flexDirection: 'row',
                        justifyContent: 'space-around'
                    }}>
                    <Text style={labelStyle}>Date</Text>
                    <DatePicker
                        style={dateStyle}
                        date={this.state.datetime}
                        mode="datetime"
                        placeholder="select date"
                        format="'MMMM Do YYYY, h:mm:ss a'"
                        confirmBtnText="Confirm"
                        cancelBtnText="Cancel"
                        customStyles={{
                            dateIcon: {
                                position: 'absolute',
                                right: 0,
                                top: 4,
                                marginRight: 0
                            },
                            dateInput: {
                                marginRight: 36,
                                borderColor: '#fff'
                            }
                        }}
                        onDateChange={datetime => this.setState({ datetime })}
                    />
                </View>
                <View style={{ flexDirection: 'row', justifyContent: 'center', flex: 1 }}>
                    <View style={{ flex: 1 }}>
                        <Button
                            disabled={!this.state.datetime || !this.state.staff}
                            onPress={() => {
                                this.onAppointmentSaved();
                                this.props.onButtonPressed()
                            }}
                            title="Save"
                            backgroundColor={APP_COLORS.MAIN_THEME}
                            icon={
                                {
                                    name: 'ios-checkmark-circle-outline',
                                    type: 'ionicon',
                                    size: 20
                                }
                            }
                            borderRadius={5}
                            fontWeight="bold"
                            disabledStyle={
                                { backgroundColor: APP_COLORS.MAIN_THEME_DISABLED }
                            } />
                    </View>
                    <View style={{ flex: 1 }}>
                        <Button
                            onPress={this.props.onButtonPressed.bind(this)}
                            title="Cancel"
                            backgroundColor={APP_COLORS.RED}
                            icon={
                                {
                                    name: 'ios-close-circle-outline',
                                    type: 'ionicon',
                                    size: 20
                                }
                            }
                            borderRadius={5}
                            fontWeight="bold" />
                    </View>
                </View>
            </View >
        );
    }
}

const styles = {
    labelStyle: {
        fontSize: 18,
        paddingLeft: 20,
        flex: 1
    },
    dateStyle: {
        flex: 2,
    },
    selectStyle: {
        flex: 1,
        borderColor: APP_COLORS.WHITE
    }
};

const mapStateToProps = state => {
    return {
        staffAvailable: state.staffAvailable,
        uid: state.uid
    }
}

const mapDispatchToProps = dispatch => {
    return {
        addUserAppointment: (uid, appointment) => {
            dispatch(addUserAppointmentsAction(uid, appointment))
        }
    }
}

export default connect(mapStateToProps, mapDispatchToProps)(AppointmentDetails);